version: "3.5"

networks:
  ingress:
    name: traefik-public
    external: true
  bus:
    name: bus
    external: true
  internal-articleservice:
    name: internal-articleservice

services:
  mongodb:
    image: mongo:4.2.5
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "root"
    networks:
      - internal-articleservice

  mongo-viewer:
    image: mongo-express:0.54
    restart: always
    ports:
      - "8084:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "articleservicedb"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root"
    networks:
      - internal-articleservice
    links:
      - "mongodb:mongo"

  bus:
    image: rabbitmq:3.8-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    ports:
      - "8083:15672"
      - "5672:5672"
    networks:
      - internal-articleservice